# Generated by Django 2.1.4 on 2018-12-28 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('post_id', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
